json.extract! business,
    :id, 
    :name, 
    :address, 
    :state, 
    :city, 
    :zipcode,
    :opentime, 
    :closetime, 
    :phone_number, 
    :website, 
    :price,
    :latitude, 
    :longitude, 
    :categories
json.photoUrls business.photos.map { |file| url_for(file) }